# Generated by Django 4.2.1 on 2023-05-28 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_panier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='panier',
            old_name='commandes',
            new_name='articles',
        ),
    ]
