# Generated by Django 4.2.1 on 2023-05-28 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shopper',
            options={'verbose_name': 'Compte Utilisateur', 'verbose_name_plural': "Les comptes d'utilisateurs"},
        ),
    ]
